# Initializing

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df=pd.read_csv('Adidas Vs Nike.csv')

# Visualizing the Data

In [36]:
df.shape

(3268, 11)

In [5]:
# The data has 3,268 rows and 10 columns

In [6]:
df.head(15)

,Product Name,Product ID,Listing Price,Sale Price,Discount,Brand,Description,Rating,Reviews,Last Visited
0,Women's adidas Originals NMD_Racer Primeknit S...,AH2430,14999,7499,50,Adidas Adidas ORIGINALS,Channeling the streamlined look of an '80s rac...,4.8,41,2020-04-13T15:06:14
1,Women's adidas Originals Sleek Shoes,G27341,7599,3799,50,Adidas ORIGINALS,"A modern take on adidas sport heritage, tailor...",3.3,24,2020-04-13T15:06:15
2,Women's adidas Swim Puka Slippers,CM0081,999,599,40,Adidas CORE / NEO,These adidas Puka slippers for women's come wi...,2.6,37,2020-04-13T15:06:15
3,Women's adidas Sport Inspired Questar Ride Shoes,B44832,6999,3499,50,Adidas CORE / NEO,"Inspired by modern tech runners, these women's...",4.1,35,2020-04-13T15:06:15
4,Women's adidas Originals Taekwondo Shoes,D98205,7999,3999,50,Adidas ORIGINALS,This design is inspired by vintage Taekwondo s...,3.5,72,2020-04-13T15:06:15
5,Women's adidas Sport Inspired Duramo Lite 2.0 ...,B75586,4799,1920,60,Adidas CORE / NEO,Refine your interval training in these women's...,1.0,45,2020-04-13T15:06:15
6,Women's adidas Sport Inspired Duramo Lite 2.0 ...,CG4051,4799,2399,50,Adidas CORE / NEO,Refine your interval training in these women's...,4.4,2,2020-04-13T15:06:15
7,Women's adidas Swim Puka Slippers,CM0080,999,599,40,Adidas CORE / NEO,These adidas Puka slippers for women's come wi...,2.8,7,2020-04-13T15:06:15
8,WOMEN'S ADIDAS RUNNING DURAMO 9 SHOES,B75990,5599,2799,50,Adidas CORE / NEO,These women's neutral running shoes will get y...,4.5,16,2020-04-13T15:06:15
9,Men's adidas Originals Forest Grove Shoes,EE5761,6599,3959,40,Adidas ORIGINALS,The Forest Grove brings back the look of the a...,4.0,39,2020-04-13T15:06:15
10,Women's adidas Originals Swift Run Shoes,EE4553,7599,4559,40,Adidas ORIGINALS,The Swift distills decades of adidas heritage ...,2.7,36,2020-04-13T15:06:16
11,Women's adidas Originals Continental Vulc Shoes,EF9315,6599,3959,40,Adidas ORIGINALS,These low-profile shoes come in a pastel color...,4.2,35,2020-04-13T15:06:16
12,Women's adidas Running Duramo 9 Shoes,F35281,5999,2999,50,Adidas CORE / NEO,These women's neutral running shoes will get y...,2.6,97,2020-04-13T15:06:16
13,Women's adidas Originals Supercourt Shoes,EF9220,7599,4559,40,Adidas ORIGINALS,"Forty years of court style, refined to the ess...",3.1,62,2020-04-13T15:06:16
14,Men's adidas Sport Inspired Response Trail Shoes,EG0000,7999,3999,50,Adidas CORE / NEO,"When the road turns to trail, all that matters...",3.2,16,2020-04-13T15:06:16

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3268 entries, 0 to 3267
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product Name   3268 non-null   object
 1   Product ID     3268 non-null   object
 2   Listing Price  3268 non-null   int64
 3   Sale Price     3268 non-null   int64
 4   Discount       3268 non-null   int64
 5   Brand          3268 non-null   object
 6   Description    3265 non-null   object
 7   Rating         3268 non-null   float64
 8   Reviews        3268 non-null   int64
 9   Last Visited   3268 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 255.4+ KB

In [12]:
df.columns=['Product_Name','Product_ID','Listing_Price','Sale_Price','Discount','Brand','Description','Rating','Reviews','Last_Visited']

In [15]:
#Since the name of the columns´ names were written with spaces, it was giving me problems when I tried to change the date format, so I decided to change the name of the columns adding a bar rather than the spaces.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3268 entries, 0 to 3267
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_Name   3268 non-null   object
 1   Product_ID     3268 non-null   object
 2   Listing_Price  3268 non-null   int64
 3   Sale_Price     3268 non-null   int64
 4   Discount       3268 non-null   int64
 5   Brand          3268 non-null   object
 6   Description    3265 non-null   object
 7   Rating         3268 non-null   float64
 8   Reviews        3268 non-null   int64
 9   Last_Visited   3268 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 255.4+ KB

In [8]:
#The last Visited column is a date column, however it needs to be modified to_date time in order to be readed.

# Changing the Date Format of Column 9

In [9]:
#First, I am going to change the format, then I am going ask it to get the weekday and add it to a new column called "day_of_the_week"

In [14]:
df['Last_Visited']=pd.to_datetime(df.Last_Visited)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3268 entries, 0 to 3267
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_Name   3268 non-null   object
 1   Product_ID     3268 non-null   object
 2   Listing_Price  3268 non-null   int64
 3   Sale_Price     3268 non-null   int64
 4   Discount       3268 non-null   int64
 5   Brand          3268 non-null   object
 6   Description    3265 non-null   object
 7   Rating         3268 non-null   float64
 8   Reviews        3268 non-null   int64
 9   Last_Visited   3268 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 255.4+ KB

In [17]:
#As you can see the Last_Visited column is changed from object to datetime.

In [33]:
df['day_of_the_week']=df.Last_Visited.dt.day_of_week

In [19]:
#The code written on line 18 is taking from Last_Visited column the day of the week and placing that info in a new column called "day_of_the_week".

In [38]:
df.head(5)

,Product_Name,Product_ID,Listing_Price,Sale_Price,Discount,Brand,Description,Rating,Reviews,Last_Visited,day_of_the_week
0,Women's adidas Originals NMD_Racer Primeknit S...,AH2430,14999,7499,50,Adidas Adidas ORIGINALS,Channeling the streamlined look of an '80s rac...,4.8,41,2020-04-13 15:06:14,0
1,Women's adidas Originals Sleek Shoes,G27341,7599,3799,50,Adidas ORIGINALS,"A modern take on adidas sport heritage, tailor...",3.3,24,2020-04-13 15:06:15,0
2,Women's adidas Swim Puka Slippers,CM0081,999,599,40,Adidas CORE / NEO,These adidas Puka slippers for women's come wi...,2.6,37,2020-04-13 15:06:15,0
3,Women's adidas Sport Inspired Questar Ride Shoes,B44832,6999,3499,50,Adidas CORE / NEO,"Inspired by modern tech runners, these women's...",4.1,35,2020-04-13 15:06:15,0
4,Women's adidas Originals Taekwondo Shoes,D98205,7999,3999,50,Adidas ORIGINALS,This design is inspired by vintage Taekwondo s...,3.5,72,2020-04-13 15:06:15,0

In [39]:
#The Column "day_of_the_week" is showing the days in numbers from 0 to 6 (Monday is 0 to Sunday which is 6).  As you can see in the Last_Visited column all the dates are on April 13th which was a Monday, that´s why all the values are zero.